spring:
  profiles: dev
  datasource:
    url: jdbc:h2:~/h2data/boilerplate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
  mustache:
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  mvc:
    static-path-pattern: /static/**
environment:
  hello: world

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
environment:
  hello: world